# 📂 Data Wrangling & File Handling in Various Formats in Python
*(Reading / Writing Text, TSV, JSON Files in Python)*

## 📌 Introduction
In real-world data analysis, information comes in different file formats like **Text (.txt)**, **TSV (.tsv)**, and **JSON (.json)**.  

Python provides **built-in** and **library-based tools** to read, write, and process these formats efficiently.  

This topic helps us learn how to **load data from different sources** and prepare it for analysis and modeling.

## Introduction to File Formats  

### Text Files (.txt)  
- Plain text without structured formatting.  
- Used for simple data storage (e.g., logs, notes).  
- Handled via Python’s built-in `open()` function.

### Writing to a text file using built-in open() function

In [2]:
# Writing to a text file using built-in open() function

with open('example_test.txt', 'w') as file:
    file.write("This is sample file for text.\n")
    file.write("This is sample file for text.\n")

print("file created successfully")

file created successfully

In [12]:
with open('example_test2.txt', 'w') as file:
    for i in range(5):
        file.write(f"this is line {i+1}\n")

print('file created sucessfuly !')

file created sucessfuly !

### Reading Text file using open()

In [13]:
with open('example_test2.txt', 'r') as file:
    data=file.read()
    print(data)

this is line 1
this is line 2
this is line 3
this is line 4
this is line 5

In [17]:
with open('example_test2.txt', 'r') as file:
    print(file.readlines())

['this is line 1\n', 'this is line 2\n', 'this is line 3\n', 'this is line 4\n', 'this is line 5\n']

## TSV (Tab-Separated Values)

- Stores tabular data with tabs (`\t`) as delimiters.  
- Similar to CSV but uses tabs instead of commas.  
- Ideal for datasets with fields containing commas.

### Compatibility with Tools:
- TSV works seamlessly with spreadsheet software (Excel, Google Sheets), databases, and data analysis tools (Pandas, R).

### Avoiding Parsing Issues:
- TXT files with spaces/commas can cause ambiguity (e.g., "New York" vs. two columns).  
- TSV’s tabs are unambiguous delimiters.  

### Efficiency:
- TSV is more compact than CSV for certain data (e.g., when text contains commas).

In [21]:
import pandas as pd

data = {
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Rahul Sharma', 'Priya Patel', 'Amit Singh', 'Neeta Rao'],
    'Department': ['HR', 'Finance', 'IT', 'Marketing'],
    'Salary (₹)': [50000, 65000, 80000, 55000],
    'Joining_Date': ['2020-01-15', '2019-05-22', '2021-11-10', '2022-03-05'],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad']
}

In [26]:
df=pd.DataFrame(data)
df

   Emp_ID          Name Department  Salary (₹) Joining_Date       City
0     101  Rahul Sharma         HR       50000   2020-01-15     Mumbai
1     102   Priya Patel    Finance       65000   2019-05-22      Delhi
2     103    Amit Singh         IT       80000   2021-11-10  Bangalore
3     104     Neeta Rao  Marketing       55000   2022-03-05  Hyderabad

In [31]:
df.to_csv('tab_example.tsv',sep='\t',index=False)

### Key Concepts:

- **sep='\t'**: Specifies tab as the delimiter.  
- **index=False**: Avoids writing row indices (by default).  
- **index=True**: If your DataFrame has a custom index (e.g., dates, employee IDs) that you want to preserve.

# Reading TSV File

In [32]:
df_read=pd.read_csv('tab_example.tsv',sep='\t')

In [33]:
df_read

   Emp_ID          Name Department  Salary (₹) Joining_Date       City
0     101  Rahul Sharma         HR       50000   2020-01-15     Mumbai
1     102   Priya Patel    Finance       65000   2019-05-22      Delhi
2     103    Amit Singh         IT       80000   2021-11-10  Bangalore
3     104     Neeta Rao  Marketing       55000   2022-03-05  Hyderabad

### Same Data, Different Formats

| Data Example      | CSV Format (Commas)                | TSV Format (Tabs)           |
|-------------------|------------------------------------|-----------------------------|
| **Simple Data**   | Apple,1.99,Red                     | Apple    1.99    Red        |
| **Data with Commas** | "Apple, Green",1.99,Green       | Apple, Green    1.99    Green |
| **Data with Quotes** | "Apple \"Honey\"",2.50,Yellow   | Apple    "Honey"    2.50    Yellow |
| **Readability**   | Harder (quotes/escapes)            | Cleaner (no conflicts)      |

### When to Use Which?

**Use CSV when:**
- Working with Excel/Google Sheets (default format).
- Data is simple (no commas in text).

**Use TSV when:**
- Data contains commas, quotes, or multi-line text.
- Processing logs, NLP data, or large datasets.

### JSON (JavaScript Object Notation)

- Lightweight data interchange format.  
- Uses key-value pairs and nested structures.  
- Commonly used for APIs and configuration files.

# creating JSON with multiple lines

In [34]:
import json

data = {
    "employees": [
        {"name": "John", "age": 30, "department": "Sales"},
        {"name": "Meera", "age": 25, "department": "Marketing"},
        {"name": "Rahul", "age": 35, "department": "HR"}
    ]
}

# Writing the dictionary to a JSON file
with open('json_example.json', 'w') as file:
    json.dump(data, file, indent=4)

- `json.dump(data, file, indent=4)`:  
  This function writes the dictionary `data` into the file in JSON format.  

- `data`: This is the dictionary you want to write to the JSON file.  

- `file`: This refers to the file object created in the `with` statement.  
  It’s where the JSON data will be written.  

- `indent=4`: This argument makes the JSON file more readable by adding  
  an indentation of 4 spaces to each level in the data hierarchy.  
  This makes it easier to read when you open the file.

## Reading the JSON file

In [35]:
import json

# Reading the JSON file
with open('json_example.json', 'r') as file:
    data = json.load(file)

# Printing the data in a more readable format
print("Employees Information:")
for em in data['employees']:
    print(f"Name: {em['name']}, Age: {em['age']}, Department: {em['department']}")

Employees Information:
Name: John, Age: 30, Department: Sales
Name: Meera, Age: 25, Department: Marketing
Name: Rahul, Age: 35, Department: HR

### File Formats Summary  

| **Format** | **Structure**   | **Best For**        | **Python Tools**                     |
|------------|-----------------|----------------------|--------------------------------------|
| **TXT**    | Raw text        | Logs, notes         | `open()`                             |
| **CSV**    | Comma tables    | Excel data          | `csv` module / `pandas`              |
| **TSV**    | Tab tables      | Text with commas    | `csv` (with `delimiter='\t'`)        |
| **JSON**   | Nested data     | APIs, configs       | `json` module                        |