### 📊 Data Preprocessing: Scaling, Encoding, Normalization (with scikit-learn)

**Concept: What is Data Preprocessing?**

Data preprocessing transforms raw data into a clean and usable format.  
It improves model performance and training speed.  

**Common tasks:**
- Handling missing values  
- Scaling numerical features  
- Encoding categorical variables  
- Normalizing feature ranges

## 🔹 Feature Scaling  

**Scaling adjusts values so features contribute equally.**

**Common techniques:**  
- **StandardScaler** (Z-score normalization)  
- **MinMaxScaler** (0–1 scale)

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Example dataset
numeric_data = pd.DataFrame({
    'Salary': [30000, 45000, 60000, 80000, 120000],
    'Age': [25, 32, 47, 51, 62]
})

numeric_data

   Salary  Age
0   30000   25
1   45000   32
2   60000   47
3   80000   51
4  120000   62

# fit_transform() does two steps at once:

## 1. fit(): Learns the mean & standard deviation of your data
## 2. transform(): Applies the scaling (converts data to Z-scores)

## For StandardScaler: Each feature becomes mean = 0, std = 1

In [3]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Standard Scaling (Z-score)
std_scaler = StandardScaler()
scaled_std = std_scaler.fit_transform(numeric_data)

df = pd.DataFrame(scaled_std, columns=numeric_data.columns)

print("\nStandard Scaled Data:\n")
df

Standard Scaled Data:

     Salary       Age
0 -1.184341 -1.382872
1 -0.704203 -0.856780
2 -0.224065  0.270562
3  0.416120  0.571186
4  1.696489  1.397904

## Min-Max Scaling (0 to 1 range)

In [4]:
minmax_scaler = MinMaxScaler()
scaled_minmax = minmax_scaler.fit_transform(numeric_data)

# Output in DataFrame
print("\nMin-Max Scaled Data:\n", pd.DataFrame(scaled_minmax, columns=numeric_data.columns))

Min-Max Scaled Data:
      Salary       Age
0  0.000000  0.000000
1  0.166667  0.189189
2  0.333333  0.594595
3  0.555556  0.702703
4  1.000000  1.000000

"""
### 🔹 StandardScaler vs MinMaxScaler Ranges

**1. MinMaxScaler**
- **Typical Range:** [0, 1]  
- **What It Means:**  
  - Squeezes the data into a fixed **0-1 range**.  
  - Formula: (X - Xmin) / (Xmax - Xmin)  

**2. StandardScaler**
- **Typical Range:** No fixed range  
- **What It Means:**  
  - Scales the data to have **mean = 0** and **standard deviation = 1**.  
  - Most values fall between **-3 and +3** (covers 99% of data).  
  - Outliers are preserved (values can be larger or smaller).  
"""

# 📌 2.Encoding Categorical Variables
# Convert text labels to numeric format for ML models

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Sample data
cat_data = pd.DataFrame({
    'Department': ['HR', 'Sales', 'IT', 'HR', 'IT']
})

cat_data

  Department
0         HR
1      Sales
2         IT
3         HR
4         IT

## 🔹 Label Encoding

In [6]:
# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform Department column
# creating another column named as-> Dept_Lable
cat_data['Dept_Label'] = label_encoder.fit_transform(cat_data['Department'])

# Print encoded data
# print("\nLabel Encoded:\n", cat_data)
cat_data

  Department  Dept_Label
0         HR           0
1      Sales           2
2         IT           1
3         HR           0
4         IT           1

### 🔹 How `fit_transform()` works in Label Encoding

- **fit()**: Learns all unique categories in the column  
  Example: `['HR', 'Sales', 'IT']`

- **transform()**: Converts each category to a number  
  Example:  
  - HR → 0  
  - IT → 1  
  - Sales → 2  

👉 Together, `fit_transform()` does both steps at once.

# One-Hot Encoding - alternative to Label Encoding

In [7]:
# One-Hot Encoding using get_dummies()
cat_data_ohe = pd.get_dummies(cat_data['Department'], prefix='Dept')

print("\nOne-Hot Encoded:\n\n", cat_data_ohe)

One-Hot Encoded:

    Dept_HR  Dept_IT  Dept_Sales
0     True    False       False
1    False    False        True
2    False     True       False
3     True    False       False
4    False     True       False

### 🔹 Normalization

**Concept:**  
Normalize data such that **row vector magnitudes = 1**

---

#### ✅ Why Use Normalizer?
- Scales each row to have **unit magnitude (length = 1)**.  
- Preserves direction of the vector.

---

#### 🔑 Key Idea:
- Converts row vectors into *pure direction form*.  
- Achieved by dividing by their **Euclidean norm**:  
  \[
  \sqrt{x_1^2 + x_2^2 + ...}
  \]

---

#### 📌 When to Use:
- **Text Data** (TF-IDF word counts)  
- **Clustering** (K-means, cosine similarity)  
- Any algorithm sensitive to vector magnitudes but not their lengths  
  (e.g., NLP, recommender systems).

In [8]:
from sklearn.preprocessing import Normalizer
# Example data
X = np.array([[3.0, 4.0], [1.0, 0.0], [0.0, 8.0]])
print("\nOriginal Data:\n", X)

# Apply Normalization
normalizer = Normalizer()
normalized_data = normalizer.fit_transform(X)

print("\nNormalized Data:\n", normalized_data)

Original Data:
 [[3. 4.]
 [1. 0.]
 [0. 8.]]

Normalized Data:
 [[0.6 0.8]
 [1.  0. ]
 [0.  1. ]]

### 🔹 Normalization Example (Step by Step)

#### First Row: [3.0, 4.0]
- Norm = √(3² + 4²) = √(9 + 16) = 5  
- Normalized = [3/5, 4/5] = [0.6, 0.8]  

#### Second Row: [1.0, 0.0]
- Norm = √(1² + 0²) = 1  
- Normalized = [1/1, 0/1] = [1.0, 0.0]  

#### Third Row: [0.0, 8.0]
- Norm = √(0² + 8²) = √(64) = 8  
- Normalized = [0/8, 8/8] = [0.0, 1.0]

## 🏬 Case Study: Retail Customer Data

**Scenario:**  
You have a retail customer dataset with **income, age, and gender**.  

👉 Goal: Prepare it for **ML model input**.

In [9]:
# Sample retail customer dataset
raw_data = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104, 105],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'Age': [23, 45, 31, 35, 52],
    'Income': [25000, 52000, 38000, 45000, 61000]
})

raw_data

   CustomerID  Gender  Age  Income
0         101    Male   23   25000
1         102  Female   45   52000
2         103  Female   31   38000
3         104    Male   35   45000
4         105  Female   52   61000

In [10]:
# Drop ID (not useful for training)
data = raw_data.drop(columns='CustomerID')
data

   Gender  Age  Income
0    Male   23   25000
1  Female   45   52000
2  Female   31   38000
3    Male   35   45000
4  Female   52   61000

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Create LabelEncoder object
label_encoder = LabelEncoder()

# Encode Gender column
data['Gender'] = label_encoder.fit_transform(data['Gender'])

# Show updated dataframe
data

   Gender  Age  Income
0       1   23   25000
1       0   45   52000
2       0   31   38000
3       1   35   45000
4       0   52   61000

In [13]:
from sklearn.preprocessing import MinMaxScaler

# Apply MinMax Scaling on Age and Income
minmax_scaler = MinMaxScaler()
scaled = minmax_scaler.fit_transform(data[['Age', 'Income']])

data[['Age', 'Income']] = scaled

print("\nProcessed Retail Data:\n", data)

Processed Retail Data:
    Gender       Age    Income
0       1  0.000000  0.000000
1       0  0.758621  0.750000
2       0  0.275862  0.361111
3       1  0.413793  0.555556
4       0  1.000000  1.000000