In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('academic.csv')

In [5]:
df

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15.0,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,NaN,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10.0,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30.0,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,0.0,50,12,50,No,Bad,Above-7,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,F,Jordan,Jordan,MiddleSchool,G-08,A,Chemistry,S,Father,5.0,4,5,8,No,Bad,Above-7,L
476,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,F,Father,50.0,77,14,28,No,Bad,Under-7,M
477,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,S,Father,55.0,74,25,29,No,Bad,Under-7,M
478,F,Jordan,Jordan,MiddleSchool,G-08,A,History,F,Father,30.0,17,14,57,No,Bad,Above-7,L
479,F,Jordan,Jordan,MiddleSchool,G-08,A,History,S,Father,35.0,14,23,62,No,Bad,Above-7,L

In [4]:
df.head()

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15.0,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,NaN,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10.0,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30.0,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,0.0,50,12,50,No,Bad,Above-7,M

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    478 non-null    object
 1   NationalITy               480 non-null    object
 2   PlaceofBirth              480 non-null    object
 3   StageID                   480 non-null    object
 4   GradeID                   480 non-null    object
 5   SectionID                 480 non-null    object
 6   Topic                     480 non-null    object
 7   Semester                  480 non-null    object
 8   Relation                  480 non-null    object
 9   raisedhands               478 non-null    float64
 10  VisITedResources          480 non-null    int64
 11  AnnouncementsView         480 non-null    int64
 12  Discussion                480 non-null    int64
 13  ParentAnsweringSurvey     480 non-null    object
 14  ParentschoolSatisfaction  480 non-null    object
 15  StudentAbsenceDays        480 non-null    object
 16  Class                     480 non-null    object
dtypes: float64(1), int64(3), object(13)
memory usage: 63.9+ KB

In [6]:
print('missing values:\n',df.isnull().sum())

missing values:
 gender                      2
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     0
SectionID                   0
Topic                       0
Semester                    0
Relation                    0
raisedhands                 2
VisITedResources            0
AnnouncementsView           0
Discussion                  0
ParentAnsweringSurvey       0
ParentschoolSatisfaction    0
StudentAbsenceDays          0
Class                       0
dtype: int64

In [7]:
print('missing values:\n',df.isnull())

missing values:
      gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0     False        False         False    False    False      False  False
1     False        False         False    False    False      False  False
2     False        False         False    False    False      False  False
3     False        False         False    False    False      False  False
4     False        False         False    False    False      False  False
..      ...          ...           ...      ...      ...        ...    ...
475   False        False         False    False    False      False  False
476   False        False         False    False    False      False  False
477   False        False         False    False    False      False  False
478   False        False         False    False    False      False  False
479   False        False         False    False    False      False  False

     Semester  Relation  raisedhands  VisITedResources  AnnouncementsView  \
0       False     False        False             False              False
1       False     False         True             False              False
2       False     False        False             False              False
3       False     False        False             False              False
4       False     False        False             False              False
..        ...       ...          ...               ...                ...
475     False     False        False             False              False
476     False     False        False             False              False
477     False     False        False             False              False
478     False     False        False             False              False
479     False     False        False             False              False

     Discussion  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0         False                  False                     False
1         False                  False                     False
2         False                  False                     False
3         False                  False                     False
4         False                  False                     False
..          ...                    ...                       ...
475       False                  False                     False
476       False                  False                     False
477       False                  False                     False
478       False                  False                     False
479       False                  False                     False

     StudentAbsenceDays  Class
0                 False  False
1                 False  False
2                 False  False
3                 False  False
4                 False  False
..                  ...    ...
475               False  False
476               False  False
477               False  False
478               False  False
479               False  False

[480 rows x 17 columns]

In [9]:
df['raisedhands']#before imputation

0      15.0
1       NaN
2      10.0
3      30.0
4       0.0
       ...
475     5.0
476    50.0
477    55.0
478    30.0
479    35.0
Name: raisedhands, Length: 480, dtype: float64

In [8]:
raisedhands_median=df['raisedhands'].median()
print(raisedhands_median)

50.0

In [10]:
df['raisedhands'].fillna(raisedhands_median,inplace=True)

In [11]:
df['raisedhands']#after imputation

0      15.0
1      50.0
2      10.0
3      30.0
4       0.0
       ...
475     5.0
476    50.0
477    55.0
478    30.0
479    35.0
Name: raisedhands, Length: 480, dtype: float64

In [12]:
print('missing values:\n',df.isnull().sum())

missing values:
 gender                      2
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     0
SectionID                   0
Topic                       0
Semester                    0
Relation                    0
raisedhands                 0
VisITedResources            0
AnnouncementsView           0
Discussion                  0
ParentAnsweringSurvey       0
ParentschoolSatisfaction    0
StudentAbsenceDays          0
Class                       0
dtype: int64

In [14]:
gender_null=df['gender'].isna().sum()#catogorical data
print(gender_null)

2

In [15]:
df['gender']

0      M
1      M
2      M
3      M
4      M
      ..
475    F
476    F
477    F
478    F
479    F
Name: gender, Length: 480, dtype: object

In [17]:
#fill gender with mode
df['gender'].mode()[0]

'M'

In [18]:
df['gender'].mode()

0    M
Name: gender, dtype: object

In [19]:
gender_mode=df['gender'].mode()[0]

In [20]:
df['gender'].fillna(gender_mode,inplace=True)

In [24]:
null_values=df['gender'].isna().sum()
print('null values in gender:\n',null_values)

null values in gender:
 0

In [25]:
df.isna().sum()

gender                      0
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     0
SectionID                   0
Topic                       0
Semester                    0
Relation                    0
raisedhands                 0
VisITedResources            0
AnnouncementsView           0
Discussion                  0
ParentAnsweringSurvey       0
ParentschoolSatisfaction    0
StudentAbsenceDays          0
Class                       0
dtype: int64

In [27]:
#shortcut
df.groupby('gender')['raisedhands'].mean()

gender
F    52.770115
M    43.643791
Name: raisedhands, dtype: float64

In [28]:
df.groupby('gender')['raisedhands'].max()

gender
F    100.0
M    170.0
Name: raisedhands, dtype: float64

In [26]:
gender_group=df.groupby('gender')
print(gender_group['raisedhands'].mean())

gender
F    52.770115
M    43.643791
Name: raisedhands, dtype: float64

In [6]:
print(df.head())

  gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father         15.0                16                  2
1        F   Father          NaN                20                  3
2        F   Father         10.0                 7                  0
3        F   Father         30.0                25                  5
4        F   Father          0.0                50                 12

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good
1          25                   Yes                     Good
2          30                    No                      Bad
3          35                    No                      Bad
4          50                    No                      Bad

  StudentAbsenceDays Class
0            Under-7     M
1            Under-7     M
2            Above-7     L
3            Above-7     L
4            Above-7     M

In [7]:
df.describe()

       raisedhands  VisITedResources  AnnouncementsView  Discussion
count   478.000000        480.000000         480.000000  480.000000
mean     46.939331         54.797917          37.918750   43.283333
std      31.375699         33.080007          26.611244   27.637735
min       0.000000          0.000000           0.000000    1.000000
25%      15.000000         20.000000          14.000000   20.000000
50%      50.000000         65.000000          33.000000   39.000000
75%      75.000000         84.000000          58.000000   70.000000
max     170.000000         99.000000          98.000000   99.000000

In [8]:
df.isna().sum()

gender                      2
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     0
SectionID                   0
Topic                       0
Semester                    0
Relation                    0
raisedhands                 2
VisITedResources            0
AnnouncementsView           0
Discussion                  0
ParentAnsweringSurvey       0
ParentschoolSatisfaction    0
StudentAbsenceDays          0
Class                       0
dtype: int64

In [9]:
df2=pd.read_csv('austin_weather.csv')

In [10]:
df2.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,

In [11]:
df2.isna().sum()

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
dtype: int64